"""Lossless compact delivery of the existing complete center-search index.

The original data file remains the source for existing maintenance scripts.
Only the compact asset is referenced by the public national-center page.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/center-search-data.js'
DEST = ROOT / 'assets/center-search-index.js'


def read_source(path=SOURCE):
    raw = path.read_text(encoding='utf-8-sig')
    return json.loads(raw[raw.index('['):raw.rindex(']') + 1])


def search_text(title, group, url):
    return ' '.join((title, group[1], group[3], ' '.join(url.strip('/').split('/')[1:])))


def pack(rows):
    groups, group_ids, entries = [], {}, []
    for row in rows:
        if set(row) != {'title', 'region', 'regionName', 'kind', 'parent', 'url', 'search'}:
            raise ValueError('Unexpected search record fields; update the codec before generating')
        group = tuple(row[k] for k in ('region', 'regionName', 'kind', 'parent'))
        if group not in group_ids:
            group_ids[group] = len(groups)
            groups.append(group)
        entry = [row['title'], group_ids[group], row['url']]
        if row['search'] != search_text(row['title'], group, row['url']):
            entry.append(row['search'])
        entries.append(entry)
    return {'groups': groups, 'rows': entries}


def unpack(payload):
    rows = []
    for entry in payload['rows']:
        title, group_id, url = entry[:3]
        group = payload['groups'][group_id]
        rows.append(dict(title=title, region=group[0], regionName=group[1], kind=group[2], parent=group[3],
                         url=url, search=entry[3] if len(entry) == 4 else search_text(title, group, url)))
    return rows


def render(rows):
    payload = pack(rows)
    if unpack(payload) != rows:
        raise ValueError('Compact search data does not round-trip exactly')
    data = json.dumps(payload, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
    return ('/* Generated by tools/compact_center_search.py; all search records are preserved. */\n'
            'window.WAWA_CENTER_INDEX=(function(p){return p.rows.map(function(r){var g=p.groups[r[1]];'
            'return {title:r[0],region:g[0],regionName:g[1],kind:g[2],parent:g[3],url:r[2],'
            'search:r.length>3?r[3]:[r[0],g[1],g[3],r[2].replace(/^\\/|\\/$/g,"").split("/").slice(1).join(" ")].join(" ")};});})('
            + data + ');\n')


def main():
    rows = read_source()
    raw = render(rows)
    DEST.write_text(raw, encoding='utf-8', newline='\n')
    print(json.dumps({'entries': len(rows), 'sourceBytes': SOURCE.stat().st_size,
                      'deliveryBytes': DEST.stat().st_size}, ensure_ascii=False))


if __name__ == '__main__':
    main()
